---
theme: jekyll-theme-leap-day
website_title:   'IntroPython-FST'
website_tagline:
 - 'Ressources pour  "Introduction au calcul scientifique avec Python" par A. Ammar et H. Ghalila'
 your_github_username: astrax
your_github_reponame: IntroPython-FST
# ==============================================================================
#                                   HTML META
# ==============================================================================
# HTML Metadata -- for <head> section
# If you don't need a variable, delete its line or comment it out with a `#`!
# ------------------------------------------------------------------------------
title: 'IntroPython-FST'
lang:   fr
date:   December 16, 2016
author:
  - Ahmed Ammar
description:
  - 'Create your projects’ website from the README.md file and publish it
     on GitHub Pages directly from master branch...'
keywords:
  - GitHub Pages
  - website
  - README.md
  - README file
  - repository
  - repo
  - project
  - theme
  - master branch
  - pandoc
  - open source
  # ******************************************************************************
# *                             INSERT BEFORE BODY                             *
# ******************************************************************************
# You can inject some extra contents after the opening <body> tag and before the
# contents of your 'README.md' file. It will be parsed as markdown and converted
# to html by pandoc. Use raw html if you need advanced features, but remember
# that all loose text will be enclosed in <p> tags -- wrap it inside a <div> if
# you don't want it parsed as markdown!
# ------------------------------------------------------------------------------
include-before: |
    <div id="starme">
    <iframe style="float:left" src="https://ghbtns.com/github-btn.html?user=astrax&repo=IntroPython-FST&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
    <h3>🡸 Give <strong>IntroPython-FST</strong> a star!</h3>
    </div><hr>
# ******************************************************************************
# *                             INSERT AFTER BODY                              *
# ******************************************************************************
# You can also inject extra contents after those of your 'README.md' file and
# before the closing </body> tag. Same rules as for 'include-before' variable.
# ------------------------------------------------------------------------------
include-after: |
    <div id="starmereminder">
    <iframe style="float:left" src="https://ghbtns.com/github-btn.html?user=astrax&repo=IntroPython-FST&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
    <h3>🡸 Don’t forget to star <strong>IntroPython-FST</strong>!</h3>
    </div>

# ------------------------------------------------------------------------------
# DON'T REMOVE the "..." below:
...
