theme: jekyll-theme-leap-day

# ******************************************************************************
# *                             INSERT AFTER BODY                              *
# ******************************************************************************
# You can also inject extra contents after those of your 'README.md' file and
# before the closing </body> tag. Same rules as for 'include-before' variable.
# ------------------------------------------------------------------------------
include-after: |
    <div id="starmereminder">
    <iframe style="float:left" src="https://ghbtns.com/github-btn.html?user=astrax&repo=IntroPython-FST&type=star&count=true&size=large" frameborder="0" scrolling="0" width="160px" height="30px"></iframe>
    <h3>🡸 Don’t forget to star <strong>IntroPython-FST</strong>!</h3>
    </div>

# ------------------------------------------------------------------------------
