# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DoubleSlit1D.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(780, 746)
        MainWindow.setMinimumSize(QtCore.QSize(780, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mplwidget1D = MPL_WIDGET_2D(self.centralWidget)
        self.mplwidget1D.setMinimumSize(QtCore.QSize(650, 0))
        self.mplwidget1D.setObjectName(_fromUtf8("mplwidget1D"))
        self.horizontalLayout.addWidget(self.mplwidget1D)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(121, 746))
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.dockWidgetContents_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_lamda = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_lamda.setObjectName(_fromUtf8("label_lamda"))
        self.verticalLayout.addWidget(self.label_lamda)
        self.SpinBox_lambda = QtGui.QSpinBox(self.dockWidgetContents_3)
        self.SpinBox_lambda.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_lambda.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_lambda.setMinimum(400)
        self.SpinBox_lambda.setMaximum(900)
        self.SpinBox_lambda.setSingleStep(10)
        self.SpinBox_lambda.setProperty("value", 632)
        self.SpinBox_lambda.setObjectName(_fromUtf8("SpinBox_lambda"))
        self.verticalLayout.addWidget(self.SpinBox_lambda)
        self.slider_lambda = QtGui.QSlider(self.dockWidgetContents_3)
        self.slider_lambda.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_lambda.setStyleSheet(_fromUtf8("font: 12pt \"Helvetica\";"))
        self.slider_lambda.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_lambda.setMinimum(400)
        self.slider_lambda.setMaximum(900)
        self.slider_lambda.setSingleStep(10)
        self.slider_lambda.setProperty("value", 632)
        self.slider_lambda.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lambda.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_lambda.setTickInterval(50)
        self.slider_lambda.setObjectName(_fromUtf8("slider_lambda"))
        self.verticalLayout.addWidget(self.slider_lambda)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_b = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_b.setObjectName(_fromUtf8("label_b"))
        self.verticalLayout.addWidget(self.label_b)
        self.SpinBox_b = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_b.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_b.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_b.setDecimals(2)
        self.SpinBox_b.setMinimum(0.1)
        self.SpinBox_b.setMaximum(1000.0)
        self.SpinBox_b.setSingleStep(0.1)
        self.SpinBox_b.setProperty("value", 435.0)
        self.SpinBox_b.setObjectName(_fromUtf8("SpinBox_b"))
        self.verticalLayout.addWidget(self.SpinBox_b)
        self.slider_b = QtGui.QSlider(self.dockWidgetContents_3)
        self.slider_b.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_b.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_b.setMinimum(1)
        self.slider_b.setMaximum(1000)
        self.slider_b.setSingleStep(1)
        self.slider_b.setPageStep(100)
        self.slider_b.setProperty("value", 435)
        self.slider_b.setOrientation(QtCore.Qt.Horizontal)
        self.slider_b.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_b.setTickInterval(100)
        self.slider_b.setObjectName(_fromUtf8("slider_b"))
        self.verticalLayout.addWidget(self.slider_b)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.dockWidgetContents_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.SpinBox_db = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_db.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_db.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_db.setDecimals(1)
        self.SpinBox_db.setMinimum(0.0)
        self.SpinBox_db.setMaximum(500.0)
        self.SpinBox_db.setSingleStep(10.0)
        self.SpinBox_db.setProperty("value", 0.0)
        self.SpinBox_db.setObjectName(_fromUtf8("SpinBox_db"))
        self.verticalLayout.addWidget(self.SpinBox_db)
        self.slider_db = QtGui.QSlider(self.dockWidgetContents_3)
        self.slider_db.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_db.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_db.setMaximum(500)
        self.slider_db.setSingleStep(10)
        self.slider_db.setProperty("value", 0)
        self.slider_db.setOrientation(QtCore.Qt.Horizontal)
        self.slider_db.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_db.setTickInterval(50)
        self.slider_db.setObjectName(_fromUtf8("slider_db"))
        self.verticalLayout.addWidget(self.slider_db)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.SpinBox_a = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_a.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_a.setDecimals(3)
        self.SpinBox_a.setMinimum(0.0)
        self.SpinBox_a.setMaximum(10.0)
        self.SpinBox_a.setSingleStep(0.01)
        self.SpinBox_a.setProperty("value", 0.1)
        self.SpinBox_a.setObjectName(_fromUtf8("SpinBox_a"))
        self.verticalLayout.addWidget(self.SpinBox_a)
        self.slider_a = QtGui.QSlider(self.dockWidgetContents_3)
        self.slider_a.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_a.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_a.setMaximum(10)
        self.slider_a.setSingleStep(1)
        self.slider_a.setPageStep(1)
        self.slider_a.setProperty("value", 0)
        self.slider_a.setOrientation(QtCore.Qt.Horizontal)
        self.slider_a.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_a.setTickInterval(1)
        self.slider_a.setObjectName(_fromUtf8("slider_a"))
        self.verticalLayout.addWidget(self.slider_a)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_a = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_a.setObjectName(_fromUtf8("label_a"))
        self.verticalLayout.addWidget(self.label_a)
        self.SpinBox_sx = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_sx.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_sx.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_sx.setDecimals(1)
        self.SpinBox_sx.setMinimum(0.1)
        self.SpinBox_sx.setSingleStep(1.0)
        self.SpinBox_sx.setProperty("value", 5.0)
        self.SpinBox_sx.setObjectName(_fromUtf8("SpinBox_sx"))
        self.verticalLayout.addWidget(self.SpinBox_sx)
        self.slider_sx = QtGui.QSlider(self.dockWidgetContents_3)
        self.slider_sx.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_sx.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_sx.setMinimum(1)
        self.slider_sx.setMaximum(100)
        self.slider_sx.setProperty("value", 5)
        self.slider_sx.setOrientation(QtCore.Qt.Horizontal)
        self.slider_sx.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_sx.setTickInterval(10)
        self.slider_sx.setObjectName(_fromUtf8("slider_sx"))
        self.verticalLayout.addWidget(self.slider_sx)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label_f2 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_f2.setObjectName(_fromUtf8("label_f2"))
        self.verticalLayout.addWidget(self.label_f2)
        self.SpinBox_D = QtGui.QDoubleSpinBox(self.dockWidgetContents_3)
        self.SpinBox_D.setMinimumSize(QtCore.QSize(0, 20))
        self.SpinBox_D.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.SpinBox_D.setDecimals(1)
        self.SpinBox_D.setMinimum(0.1)
        self.SpinBox_D.setMaximum(50.0)
        self.SpinBox_D.setProperty("value", 1.0)
        self.SpinBox_D.setObjectName(_fromUtf8("SpinBox_D"))
        self.verticalLayout.addWidget(self.SpinBox_D)
        self.slider_D = QtGui.QSlider(self.dockWidgetContents_3)
        self.slider_D.setMinimumSize(QtCore.QSize(0, 25))
        self.slider_D.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.slider_D.setMinimum(1)
        self.slider_D.setMaximum(50)
        self.slider_D.setProperty("value", 1)
        self.slider_D.setSliderPosition(1)
        self.slider_D.setOrientation(QtCore.Qt.Horizontal)
        self.slider_D.setTickPosition(QtGui.QSlider.TicksBelow)
        self.slider_D.setTickInterval(10)
        self.slider_D.setObjectName(_fromUtf8("slider_D"))
        self.verticalLayout.addWidget(self.slider_D)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.Central_Spot = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.Central_Spot.setMinimumSize(QtCore.QSize(0, 20))
        self.Central_Spot.setObjectName(_fromUtf8("Central_Spot"))
        self.verticalLayout.addWidget(self.Central_Spot)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_4.setMinimumSize(QtCore.QSize(0, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.Internal_Spot = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.Internal_Spot.setObjectName(_fromUtf8("Internal_Spot"))
        self.verticalLayout.addWidget(self.Internal_Spot)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.dockWidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Diffraction - Fraunhofer", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Setting", None))
        self.label_lamda.setText(_translate("MainWindow", "Wavelength(nm)", None))
        self.SpinBox_lambda.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light", None))
        self.slider_lambda.setStatusTip(_translate("MainWindow", "Change the wave length of monochromatic light", None))
        self.label_b.setText(_translate("MainWindow", "<html><head/><body><p>b1( &mu;m)</p></body></html>", None))
        self.SpinBox_b.setStatusTip(_translate("MainWindow", "Change the width of the rectangular aperture", None))
        self.slider_b.setStatusTip(_translate("MainWindow", "Change the width of the rectangular aperture", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>&Delta;b( &mu;m)</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "a(cm)", None))
        self.label_a.setText(_translate("MainWindow", "sx(mm)", None))
        self.SpinBox_sx.setStatusTip(_translate("MainWindow", "Change the side of the square-shaped screen", None))
        self.slider_sx.setStatusTip(_translate("MainWindow", "Change the side of the square-shaped screen", None))
        self.label_f2.setText(_translate("MainWindow", "D(m)", None))
        self.SpinBox_D.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2", None))
        self.slider_D.setStatusTip(_translate("MainWindow", "Change the focal length f2 of the lens L2", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Central spot</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Internal Spot</span></p></body></html>", None))

from mplwidget import MPL_WIDGET_2D

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

